version: '3'  

networks:
  traefik-proxy:
    external: true

services:
  traefik-proxy:
    image: traefik:1.7
    container_name: traefik
    command: --docker
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/containers/traefik:/etc/traefik
      - ./traefik.toml:/etc/traefik/traefik.toml
    labels:
      - "traefik.frontend.rule=Host:localhost"
    networks:
      - traefik-proxy
